- name: Install postgresql-server
  dnf:
    name: postgresql-server
    state: latest

- name: Initialize postgresql database cluster
  shell:
    cmd: /usr/bin/postgresql-setup --initdb

- name: Make sure a service unit is running
  ansible.builtin.systemd_service:
    name: postgresql
    state: started
    enabled: true
    